# Generated by Django 4.1.4 on 2022-12-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmates',
            name='email',
            field=models.CharField(default='sth@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='classmates',
            name='phone',
            field=models.CharField(default='+1-1111', max_length=255),
        ),
    ]
